// <auto-generated />
using FinalProject1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220421005543_MYMigration2")]
    partial class MYMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject1.Models.AboutProduct", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutProducts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuyerID")
                        .HasColumnType("int");

                    b.Property<string>("ProductMadeCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStoreID")
                        .HasColumnType("int");

                    b.Property<int>("ProductoverviewID")
                        .HasColumnType("int");

                    b.Property<int>("Productprice")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("ProductStoreID");

                    b.HasIndex("ProductoverviewID");

                    b.ToTable("AboutProduct");
                });

            modelBuilder.Entity("FinalProject1.Models.BuyerInfo", b =>
                {
                    b.Property<int>("BuyerID")
                        .HasColumnType("int");

                    b.Property<string>("BuyerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.HasKey("BuyerID");

                    b.ToTable("BuyerInfo");
                });

            modelBuilder.Entity("FinalProject1.Models.PaymentInfo", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.ToTable("PaymentInfo");
                });

            modelBuilder.Entity("FinalProject1.Models.ProuctOverview", b =>
                {
                    b.Property<int>("ProductoverviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductParts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductoverviewID");

                    b.ToTable("ProuctOverview");
                });

            modelBuilder.Entity("FinalProject1.Models.ProuctSore", b =>
                {
                    b.Property<int>("ProductStoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StoreAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductStoreID");

                    b.ToTable("ProuctSore");
                });

            modelBuilder.Entity("FinalProject1.Models.AboutProduct", b =>
                {
                    b.HasOne("FinalProject1.Models.BuyerInfo", "BuyerInfo")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject1.Models.ProuctSore", "ProductSore")
                        .WithMany()
                        .HasForeignKey("ProductStoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject1.Models.ProuctOverview", "ProuctOverview")
                        .WithMany()
                        .HasForeignKey("ProductoverviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerInfo");

                    b.Navigation("ProductSore");

                    b.Navigation("ProuctOverview");
                });

            modelBuilder.Entity("FinalProject1.Models.BuyerInfo", b =>
                {
                    b.HasOne("FinalProject1.Models.PaymentInfo", "PaymentInfo")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
